# Docker compose version
version: "3.8"
services:
	#database:
	#kurento-media-server:
	#kurento-group-call:
	web-back:
		build:
			context: ${PWD}/backend
			dockerfile: ${PWD}/backend/Dockerfile
		container_name: ssafy_web_back
		restart: always
		ports:
			- "8080:8080"
			- "8443:8443"
		environment:
			TZ: "Asia/Seoul"
	#web-front:
